// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb8dARYUGWiK8EuaxnW4Hqq7nBoGsCjPk',
    appId: '1:1019736398698:web:908dc132acad30d0cfe313',
    messagingSenderId: '1019736398698',
    projectId: 'trasferenciab-1ec50',
    authDomain: 'trasferenciab-1ec50.firebaseapp.com',
    databaseURL: 'https://trasferenciab-1ec50-default-rtdb.firebaseio.com',
    storageBucket: 'trasferenciab-1ec50.firebasestorage.app',
    measurementId: 'G-HC177F05MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMxdOkZUHoeJOi3d5kkCWs15bO5fqYiD4',
    appId: '1:1019736398698:android:7c297094a2f4b7cfcfe313',
    messagingSenderId: '1019736398698',
    projectId: 'trasferenciab-1ec50',
    databaseURL: 'https://trasferenciab-1ec50-default-rtdb.firebaseio.com',
    storageBucket: 'trasferenciab-1ec50.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAb8dARYUGWiK8EuaxnW4Hqq7nBoGsCjPk',
    appId: '1:1019736398698:web:2ae1eed1db65f82ecfe313',
    messagingSenderId: '1019736398698',
    projectId: 'trasferenciab-1ec50',
    authDomain: 'trasferenciab-1ec50.firebaseapp.com',
    databaseURL: 'https://trasferenciab-1ec50-default-rtdb.firebaseio.com',
    storageBucket: 'trasferenciab-1ec50.firebasestorage.app',
    measurementId: 'G-Q2NGGQGGFQ',
  );
}
